<?php

return [
    [
        'lang_label' => 'Objective-C',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-objective-c.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/objectivec',
        'width'      => 34,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'Swift',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-swift.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/swift',
        'width'      => 45,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'Ruby',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-ruby.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/ruby',
        'width'      => 42,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'Python',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-python.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/python',
        'width'      => 40,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => '.NET',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-windows.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/cs',
        'width'      => 42,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'Java',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-java.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/java',
        'width'      => 36,
        'height'     => 48,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'JavaScript',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-js.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/javascript',
        'width'      => 36,
        'height'     => 40,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'PHP',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-php.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/php',
        'width'      => 68,
        'height'     => 34,
        'is_hidden'  => false,
    ],
    [
        'lang_label' => 'GO',
        'lang_image' => get_template_directory_uri() . '/assets/home-lang-go.svg',
        'lang_url'   => 'https://developer.virgilsecurity.com/docs/go',
        'width'      => 34,
        'height'     => 46,
        'is_hidden'  => false,
    ],
];
