<?php

return [
    [
        'name'             => 'Michael W. Wellman',
        'position'         => 'CEO & Founder',
        //'facebook'         => '',
        //'github'           => '',
        'twitter'          => 'https://twitter.com/virgilsecurity',
        'linkedin'         => 'https://www.linkedin.com/in/mwellman',
        //'medium'           => '',
        //'tel'              => '',
        'email'            => 'm.wellman@virgilsecurity.com',
        //'is_show_facebook' => false,
        //'is_show_github'   => false,
        'is_show_twitter'  => true,
        'is_show_linkedin' => true,
        //'is_show_medium'   => false,
        'is_show_email'    => true,
        'is_hidden'        => false,
    ],
    [
        'name'             => 'Dmitry Dain',
        'position'         => 'CTO & co-Founder',
        //'facebook'         => '',
        //'github'           => '',
        'twitter'          => 'https://twitter.com/dmitrydain',
        'linkedin'         => 'https://www.linkedin.com/in/dmitrydain',
        //'medium'           => '',
        //'tel'              => '',
        'email'            => 'd.dain@virgilsecurity.com',
        //'is_show_facebook' => false,
        //'is_show_github'   => false,
        'is_show_twitter'  => true,
        'is_show_linkedin' => true,
        //'is_show_medium'   => false,
        'is_show_email'    => true,
        'is_hidden'        => false,
    ],
];
