<?php

return [
    [
        'title'     => "C",
        'image'     => get_template_directory_uri() . '/assets/features-features-c.png',
        'width'     => 62,
        'height'    => 70,
        'is_hidden' => false,
    ],
    [
        'title'     => "C++",
        'image'     => get_template_directory_uri() . '/assets/features-features-cplusplus.png',
        'width'     => 61,
        'height'    => 70,
        'is_hidden' => false,
    ],
    [
        'title'     => "C#",
        'image'     => get_template_directory_uri() . '/assets/features-features-csharp.png',
        'width'     => 62,
        'height'    => 70,
        'is_hidden' => false,
    ],
    [
        'title'     => "JavaScript",
        'image'     => get_template_directory_uri() . '/assets/features-features-js.png',
        'width'     => 65,
        'height'    => 65,
        'is_hidden' => false,
    ],
    [
        'title'     => "Python",
        'image'     => get_template_directory_uri() . '/assets/features-features-python.png',
        'width'     => 70,
        'height'    => 70,
        'is_hidden' => false,
    ],
    [
        'title'     => "Ruby",
        'image'     => get_template_directory_uri() . '/assets/features-features-ruby.png',
        'width'     => 66,
        'height'    => 62,
        'is_hidden' => false,
    ],
    [
        'title'     => "Node",
        'image'     => get_template_directory_uri() . '/assets/features-features-node.png',
        'width'     => 61,
        'height'    => 70,
        'is_hidden' => false,
    ],
    [
        'title'     => "Swift",
        'image'     => get_template_directory_uri() . '/assets/features-features-swift.png',
        'width'     => 62,
        'height'    => 54,
        'is_hidden' => false,
    ],
    [
        'title'     => "Apple",
        'image'     => get_template_directory_uri() . '/assets/features-features-apple.png',
        'width'     => 42,
        'height'    => 50,
        'is_hidden' => false,
    ],
    [
        'title'     => "Go",
        'image'     => get_template_directory_uri() . '/assets/features-features-go.png',
        'width'     => 80,
        'height'    => 48,
        'is_hidden' => false,
    ],
    [
        'title'     => "Java",
        'image'     => get_template_directory_uri() . '/assets/features-features-java.png',
        'width'     => 59,
        'height'    => 80,
        'is_hidden' => false,
    ],
    [
        'title'     => ".Net",
        'image'     => get_template_directory_uri() . '/assets/features-features-dotnet.png',
        'width'     => 86,
        'height'    => 50,
        'is_hidden' => false,
    ],
    [
        'title'     => "PHP",
        'image'     => get_template_directory_uri() . '/assets/features-features-php.png',
        'width'     => 92,
        'height'    => 44,
        'is_hidden' => false,
    ],
    [
        'title'     => "Asmjs",
        'image'     => get_template_directory_uri() . '/assets/features-features-asmjs.png',
        'width'     => 74,
        'height'    => 58,
        'is_hidden' => false,
    ],
    [
        'title'     => "Android",
        'image'     => get_template_directory_uri() . '/assets/features-features-android.png',
        'width'     => 110,
        'height'    => 24,
        'is_hidden' => false,
    ],
    [
        'title'     => "Windows",
        'image'     => get_template_directory_uri() . '/assets/features-features-windows.png',
        'width'     => 150,
        'height'    => 32,
        'is_hidden' => false,
    ],
    [
        'title'     => "iOS",
        'image'     => get_template_directory_uri() . '/assets/features-features-ios.png',
        'width'     => 50,
        'height'    => 25,
        'is_hidden' => false,
    ],
    [
        'title'     => "MacOS",
        'image'     => get_template_directory_uri() . '/assets/features-features-macos.png',
        'width'     => 100,
        'height'    => 26,
        'is_hidden' => false,
    ],
    [
        'title'     => "FireFox",
        'image'     => get_template_directory_uri() . '/assets/features-features-ff.png',
        'width'     => 100,
        'height'    => 28,
        'is_hidden' => false,
    ],
    [
        'title'     => "Chrome",
        'image'     => get_template_directory_uri() . '/assets/features-features-chrome.png',
        'width'     => 140,
        'height'    => 36,
        'is_hidden' => false,
    ],
    [
        'title'     => "Nrf52",
        'image'     => get_template_directory_uri() . '/assets/features-features-nrf52.png',
        'width'     => 58,
        'height'    => 42,
        'is_hidden' => false,
    ],
];
